### ISSUE TITLE
Is this module still under active development?

### ISSUE THREAD

**Issue by mattmcmanus** [lloyd/node-compute-cluster#17]
Hey Lloyd, I saw you present on this module at Node.Philly last year. I'm about to start development on a project that may benefit from a module like this. Do you have any plans for further supporting & developing of it?

**Comment by j16h** [comment]
any answers so far ? :)

**Comment by randunel** [comment]
guess not :(

**Comment by Doidel** [comment]
pity

**Comment by dannycoates** [comment]
we're using it at mozilla and will be doing some maintenance now that more of us have push access, but there's similar projects on npm that are more popular and probably better maintained.
